load("uname.sky", "uname")

uname(
    name = "uname",
)

load("file.sky", "file")

file(
    name = "filemount",
    srcs = [
        "/home/sevki/src/go/src/bldy.build/build/tests/testdata/docker/BUILD",
    ],
)