deb(
    name = "clang",
    arch = "amd64",
    checksum = "sha256:d1196efc7b8f9f9a03f29ae0256bee76af90e290200185ae58e72eca950aa626",
    component = "main",
    pkg = "clang-4.0",
    release = "stretch",
    repo = "deb.debian.org/debian",
    version = "1:4.0.1-10~deb9u2",
)