// Code generated by "stringer -type Type"; DO NOT EDIT

package token

import "fmt"

const _Type_name = "EOFErrorNewlineStringSpaceNumberFloatHexLeftCurlyRightCurlyLeftParenRightParenLeftBracRightBracQuoteEqualColonCommaSemicolonPeriodCommentPlusPipeElipsisTrueFalseMultiLineStringTargetDeclFunc"

var _Type_index = [...]uint8{0, 3, 8, 15, 21, 26, 32, 37, 40, 49, 59, 68, 78, 86, 95, 100, 105, 110, 115, 124, 130, 137, 141, 145, 152, 156, 161, 176, 186, 190}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
