load("testdata/empty.bzl", "empty")

empty(
	name="test",
	src=[
		"x.c",
	],
	deps=[
		"sevki",
	]
)

load("testdata/noop.bzl", "noop")

noop(
	name="noop",
)


load("testdata/printer.bzl", "printer")
