// Code generated by "stringer -type attrType ."; DO NOT EDIT.

package skylark

import "fmt"

const _attrType_name = "_int_labelList"

var _attrType_index = [...]uint8{0, 4, 14}

func (i attrType) String() string {
	if i < 0 || i >= attrType(len(_attrType_index)-1) {
		return fmt.Sprintf("attrType(%d)", i)
	}
	return _attrType_name[_attrType_index[i]:_attrType_index[i+1]]
}
